site_name: Plataforma Vortex
site_author: Henrique Morais
site_description: >-
  Essa documentação foi criada com o intuito de ajudar os clientes
  que utilizam a Plataforma Vortex.
copyright: Copyright &copy; Veter

repo_name: vortex_docs
repo_url: https://github.com/veter-eng/vortex_docs
edit_uri: tree/main/docs

theme:
  features:
    - navigation.tabs
    - navigation.top
    - content.code.annotate
    - search.highlight
    - search.share
    - search.suggest
  name: material
  language: pt-BR
  logo: assets/vortex.png
  favicon: assets/vortex.png
  palette:
    - scheme: default
      primary: black
      accent: yellow
      toggle:
        icon: material/lightbulb
        name: Modo Noturno
    - scheme: slate
      primary: magenta
      accent: magenta
      toggle:
        icon: material/lightbulb-outline
        name: Modo Claro

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - /javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python

extra:
  alternate:
    - name: PT
      link: /pt/
      lang: pt
    - name: EN
      link: /en/
      lang: en

nav:
  - Home: index.md
  - Arquitetura:
    - Resumo: arquitetura/resumo.md
  - Proposta Comercial:
    - Vortex Server: proposta_comercial/index.md
  - Vortex Server:
    - Visão Geral: vortex_server/index.md
  - Vortex Collector:
    - Visão Geral: vortex_collector/index.md
  - Vortex API:
    - Visão Geral: vortex_api/index.md